config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  root to: 'transactions#new'
  get 'create', to: 'transactions#create'
end

app/models/transaction.rb
class Transaction < Object
  include ActiveModel::Model
  attr_accessor :bal
  attr_accessor :dep
  attr_accessor :wdl
  validates_presence_of :bal
  validates_presence_of :dep
  validates_presence_of :wdl
  
  def balance(amt1,amt2,amt3)
    @bal = amt1 + amt2 - amt3 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def new
    @transaction = Transaction.new
    render :new
  end
  
  def create
    @transaction = Transaction.new(secure_params)
    if @bal != 0.00
      bal = params[:transaction]
      @bal = @transaction.bal.to_f
      dep = params[:transaction]
      @dep = @transaction.dep.to_f
      wdl = params[:transaction]
      @wdl = @transaction.wdl.to_f

      render :create
    else
      render :new
    end
  end

  private
  
  def secure_params
    params.require(:transaction).permit(:bal, :dep, :wdl)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%#= link_to 'Transaction', new_transaction_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inventory1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Inventory1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About inventory1</h3>
<p>inventory1 is a simple bookkeeping app.<br> Given an initial balance, it adds or/and substracts a transaction to provide a final balance.</p>

app/views/transactions/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h3>Calculation Result</h3>
    <p>
      <%@transaction = Transaction.new%>
      The new balance is: <%= @transaction.balance(@bal,@dep,@wdl) %>
    </p>
  </body>
</html>

app/views/transactions/new.html.erb
<% content_for :title do %>Transaction<% end %>
<h3>Transaction</h3>
<p>Please enter a current balance, any deposit and withdrawal. </p>
<div class="form">
  <%= simple_form_for @transaction do |form| %>
    <%#= form.error_notification %>
    <%= form.input :bal, autofocus: true %>
    <%= form.input :dep %>
    <%= form.input :wdl %>
    <%= button_to "Calculate" ,:action => "create"%>
  <% end %>
</div>